# Copyright: CityU UR 
# Project: David (FuckPX4)
# Author: Ranger GUO
# Email: runzhoguo3-c@my.cityu.edu.hk
# Date: 2024-10-23
# Description: Survice of loading text file

# name of the file (must include format, like ".txt", "yaml")
string file_name

# path
string file_path

---

# return flag
bool success

# error msg
string status

# length of the filestream
uint32 length_of_data

# data of the file
string txt_data